### ISSUE TITLE
Show in interface tileX, tileY of cursor

### ISSUE THREAD

**Issue by Elrinth** [ConConner/ConConsMapMapper#14]
Would be sweet if it could show somewhere tileX and tileY you have currently hovering on map. This will help me map out my rooms for my game. Rather than having to count it myself.

Amazing editor btw! Help me make maps for my godot game! Also what is the png provided in the exported map file? It doesn't seem to work any longer. "https://cdn.discordapp.com/attachments/885112600575238194/1050460064877654096/mm_basic_markers_extended.png"

I'll share a short tutorial how to read map file from this amazing program!

**Comment by ConConner** [comment]
Hello, development has stagnated in 2022. I dont know if there will ever really be a new version.
If it helps, there is a debug menu that shows coordinates if you press F12.

The .png that is referenced in the map file are custom marker graphics. In 2022 it was still possible to have permanent links from discord. This has changed, which means that the link doesnt work anymore. The standard markers are included in the executable as well though.

**Comment by Elrinth** [comment]
Sweet! The F12 debug menu solves the problem! :)
